name: Azure Load Test

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
#   contents: write  # read is required for actions/checkout, write is required to create a release

jobs:
  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'loadtest/config.yaml'
          loadTestResource: 'jcantosz-load-test'
          resourceGroup: 'jcantosz'
          
  deploy-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      - name: "Azure Load Testing"
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az load test-run create `
            --load-test-resource jcantosz-load-test `
            --resource-group jcantosz `
            --test-id "20a63f38-aba5-4ebd-86ea-d2b27d1ef310" `
            --display-name "GitHub Actions Run $(date)" `
            --description "$env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID" `
            --test-run-id "$(date +%s)"

            # --env
      # - name: 'Azure Load Testing'
      #   uses: azure/load-testing@v1
      #   with:
      #     loadTestConfigFile: 'loadtest/config.yaml'
      #     loadTestResource: 'jcantosz-load-test'
      #     resourceGroup: 'jcantosz'
