name: AZ test webdeploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # read is required for actions/checkout, write is required to create a release
env:
  AZURE_DEFAULTS_GROUP: "${{secrets.RESOURCE_GROUP}}"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:
    uses: ./.github/workflows/r_build.yaml
    with:
      OUTPUT_PATH: "./publish"
      AZURE_WEBAPP_PACKAGE_PATH: "./publish"
      DOTNET_CORE_VERSION: "6.0.x"
      ARTIFACT_NAME: "webapp"

  deploy-dev:
    needs: build
    uses: ./.github/workflows/r_deploy_win.yaml
    with:
      ENVIRONMENT: "dev"
      ENVIRONMENT_URL: "https://dev.github.com"
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      WEBAPP_NAME: ${{ vars.webappname }}
      ARTIFACT_NAME: "webapp"
    # Pass all secrets the calling workflow has access to
    secrets: inherit
    # secrets:
    #   RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
    #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    #   AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy-qa:
    needs: deploy-dev
    uses: ./.github/workflows/r_deploy_win.yaml
    with:
      ENVIRONMENT: "qa"
      ENVIRONMENT_URL: "https://qa.github.com"
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      WEBAPP_NAME: ${{ vars.webappname }}
      ARTIFACT_NAME: "webapp"
    secrets: inherit

  get-next-version-tag:
    uses: ./.github/workflows/r_get_version_win.yaml
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prerelease:
    needs: [deploy-qa, get-next-version-tag] 
    uses: ./.github/workflows/r_release_win.yaml
    with:
      ENVIRONMENT: "prerelease"
      PRERELEASE: true
      RELEASE_VERSION: ${{ needs.get-next-version-tag.outputs.NEXT_VERSION }}
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      ARTIFACT_NAME: "webapp"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy-uat:
    needs: [prerelease, get-next-version-tag]
    uses: ./.github/workflows/r_deploy_win.yaml
    with:
      ENVIRONMENT: "uat"
      ENVIRONMENT_URL: "https://uat.github.com"
      ARTIFACT_NAME: "webapp"
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      RELEASE_VERSION: ${{ needs.get-next-version-tag.outputs.NEXT_VERSION }}
      WEBAPP_NAME: ${{ vars.webappname }}
    secrets: inherit

  release:
    needs: [deploy-uat, get-next-version-tag]
    uses: ./.github/workflows/r_release_win.yaml
    with:
      ENVIRONMENT: "release"
      PRERELEASE: false
      RELEASE_VERSION: ${{ needs.get-next-version-tag.outputs.NEXT_VERSION }}
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      ARTIFACT_NAME: "webapp"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    needs: [release, get-next-version-tag]
    uses: ./.github/workflows/r_deploy_win.yaml
    with:
      ENVIRONMENT: "prod"
      ENVIRONMENT_URL: "https://github.com"
      ARTIFACT_NAME: "webapp"
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      RELEASE_VERSION: ${{ needs.get-next-version-tag.outputs.NEXT_VERSION }}
      WEBAPP_NAME: ${{ vars.webappname }}
    secrets: inherit

