name: AZ test webdeploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
env:
  AZURE_DEFAULTS_GROUP: "${{secrets.RESOURCE_GROUP}}"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        release_number="v$(date '+%Y%m%d%H%M%S')"
        gh release create $release_number --prerelease=true --generate-notes

  build:
    uses: ./.github/workflows/r_build.yaml
    with:
      AZURE_WEBAPP_PACKAGE_PATH: "./publish"
      DOTNET_CORE_VERSION: "6.0.x"

  deploy-dev:
    needs: build
    uses: ./.github/workflows/r_deploy.yaml
    with:
      ENVIRONMENT: "dev"
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      WEBAPP_NAME: ${{ vars.webappname }}
    secrets:
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  deploy-qa:
    needs: deploy-dev
    uses: ./.github/workflows/r_deploy.yaml
    with:
      ENVIRONMENT: "qa"
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      WEBAPP_NAME: ${{ vars.webappname }}
    secrets:
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  prerelease-uat:
    needs: deploy-qa
    uses: ./.github/workflows/r_release.yaml
    with:
      ENVIRONMENT: "uat"
      PRERELEASE: "true"
      AZURE_WEBAPP_PACKAGE_PATH: "webapp"
      ARTIFACT_NAME: "webapp"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
