name: AZ test webdeploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
env:
  AZURE_DEFAULTS_GROUP: "${{secrets.RESOURCE_GROUP}}"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: webapp
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: run script
        run: |
          az webapp list
          az webapp list --resource-group ${{secrets.RESOURCE_GROUP}}
      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.webappname }}
          mask-inputs: false
          app-settings-json: '[{ "name": "SCM_DO_BUILD_DURING_DEPLOYMENT", "value": "1", "slotSetting": false }]'
#       - name: Deploy to Azure WebApp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ vars.webappname }}
#           package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
