name: workflow

on:
  [push]


jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.PUBLISH_PROFILE }}
    - name: run script
      run: echo ok 
    - uses: azure/appservice-settings@v1
      with:
        app-name: jcantosz-myapp
        slot-name: "development"
        mask-inputs: false
        general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
