name: workflow

on:
  [push]


jobs:
	my-job:
		runs-on: ubuntu-latest
		steps:
		- uses: azure/login@v1
			with:
			 creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}
		- uses: azure/appservice-settings@v1
			with:
			 app-name: ${{ env.AZURE_WEBAPP_NAME }}
			 mask-inputs: false
			 general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
