name: Build

on:
  workflow_call:
    inputs:
      AZURE_WEBAPP_PACKAGE_PATH:
        required: true
        type: string
      DOTNET_CORE_VERSION:
        required: false
        type: string
        default: "6.0.x"
      OUTPUT_PATH:
        required: false
        type: string
        default: "./publish"
      PROJECT_DIRECTORY:
        required: false
        type: string
        default: '.'
      ARTIFACT_NAME:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.DOTNET_CORE_VERSION }}
      - name: Restore
        run: dotnet restore "${{ inputs.PROJECT_DIRECTORY }}"
      - name: Build
        run: dotnet build "${{ inputs.PROJECT_DIRECTORY }}" --no-restore
      - name: Publish
        run: dotnet publish "${{ inputs.PROJECT_DIRECTORY }}" --no-build --output "${{ inputs.OUTPUT_PATH }}"
      - name: showall
          dir

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.ARTIFACT_NAME }}"
          path: "${{ inputs.AZURE_WEBAPP_PACKAGE_PATH }}"
          retention-days: 1
