name: Get Next Version

on:
  workflow_call:
    inputs:
      TAG_PREFIX:
        required: false
        type: string
        default: "v"
      FALLBACK_TAG:
        required: false
        type: string
        default: "1"
      TAG_FORMAT:
        required: false
        type: string
        default: '[0-9]+'
    secrets:
      GH_TOKEN:
        required: true
    outputs:
      NEXT_VERSION:
        description: "The next version to release"
        value: ${{ jobs.create-version.outputs.NEXT_VERSION }}

jobs:
  create-version:
    runs-on: windows-2019
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      NEXT_VERSION: ${{ steps.get-next-version.outputs.NEXT_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: get next version
        id: get-next-version
        run: |
          git fetch --tags
          $TAGS=(git tag)
          $CURR_TAG=""

          if (![string]::IsNullOrEmpty($TAGS)) {
            $CURR_TAG=(git tag | select-string "v[0-9]+" | sort-object -Descending)[0].toString().trimStart('v')
            $CURR_TAG=(([int64]$CURR_TAG) + 1)
          }

          if ([string]::IsNullOrEmpty($CURR_TAG)) {
            $CURR_TAG="${{ inputs.FALLBACK_TAG }}"
          }

          $NEXT_VERSION=("v{0:0#}" -f $CURR_TAG)

          # Set as output
          echo $NEXT_VERSION
          echo "NEXT_VERSION=$NEXT_VERSION" >> $env:GITHUB_OUTPUT



