name: test loop

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-loop
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # read is required for actions/checkout, write is required to create a release
env:
  AZURE_DEFAULTS_GROUP: "${{secrets.RESOURCE_GROUP}}"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:
    uses: ./.github/workflows/r_build_loop.yaml
    with:
      OUTPUT_PATH: "./publish"
      # package up multiple paths into the artifact
      ARTIFACT_PATHS: |
        "./publish"
        jcantosz-myapp/bin
      DOTNET_CORE_VERSION: "6.0.x"
      ARTIFACT_NAME: "webapp"
      PROJECT_DIRECTORIES: |
        .
        jcantosz-myapp
