name: test external scripts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-external
  cancel-in-progress: true

jobs:
  # Packaging scripts in a different repo
  scripts_with_extra_clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -halt
      - uses: actions/checkout@v3
        with:
          repository: jcantosz-test-org/deploy-scripts
          ref: main
          ssh-key: ${{ secrets.DEPLOY_SCRIPTS_SSH_KEY }}
          path: 'deploy_repo'
      - run: ls -halt
      - run: ls -halt ./deploy_repo
      - run: |
          bash ./deploy_repo/scripts/hello.sh

  # Packaging scripts with actions
  scripts_with_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: action no params
        uses: jcantosz-test-org/deploy-scripts@main
      - name: action deploy_webservice
        uses: jcantosz-test-org/deploy-scripts@main
        with:
          script: "deploy_webservice"
      - name: action deploy_function
        uses: jcantosz-test-org/deploy-scripts@main
        with:
          script: "deploy_function"

          
