name: test external scripts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-external
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # read is required for actions/checkout, write is required to create a release
env:
  AZURE_DEFAULTS_GROUP: "${{secrets.RESOURCE_GROUP}}"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -halt
      - uses: actions/checkout@v3
        with:
          repository: jcantosz-test-org/deploy-scripts
          ref: main
          ssh-key: ${{ secrets.DEPLOY_SCRIPTS_SSH_KEY }}
          path: 'deploy_repo'
      - run: ls -halt
      - run: ls -halt ./deploy_repo
      - run: |
          bash ./deploy_repo/scripts/hello.sh
      - name: action no params
        uses: jcantosz-test-org/deploy-scripts@main
      - name: action deploy_webservice
        uses: jcantosz-test-org/deploy-scripts@main
        with:
          script: "deploy_webservice"
      - name: action deploy_function
        uses: jcantosz-test-org/deploy-scripts@main
        with:
          script: "deploy_function"

          
