name: test enhancements

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}-enhance
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # read is required for actions/checkout, write is required to create a release
env:
  AZURE_DEFAULTS_GROUP: "${{secrets.RESOURCE_GROUP}}"
    
jobs:
  build:
    uses: ./.github/workflows/r_build.yaml
    with:
      OUTPUT_PATH: ./publish
      ARTIFACT_PATHS: |
          /home/runner/work/aspnetcore-sample/aspnetcore-sample/publish
          /home/runner/work/aspnetcore-sample/aspnetcore-sample/jcantosz-myapp/bin
          /home/runner/work/aspnetcore-sample/aspnetcore-sample/jcantosz-myapp/Pages
      DOTNET_CORE_VERSION: "6.0.x"
      ARTIFACT_NAME: "webapp"
  build-inline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Restore
        run: dotnet restore .
      - name: Build
        run: dotnet build . --no-restore
      - name: Publish
        run: dotnet publish . --no-build --output ./publish
      - name: showall
        run: |
          cd jcantosz-myapp
          dir
          pwd
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "my-arti"
          path: |
            /home/runner/work/aspnetcore-sample/aspnetcore-sample/publish
            /home/runner/work/aspnetcore-sample/aspnetcore-sample/jcantosz-myapp/bin
            /home/runner/work/aspnetcore-sample/aspnetcore-sample/jcantosz-myapp/Pages
          retention-days: 1
  deploy:
    needs: build
    uses: ./.github/workflows/r_deploy_win.yaml
    strategy:
      matrix:
        includes:
          - packagepath: "webapp"
            webappname: "user-site"
            url: dev.github.com
          - packagepath: "webapp"
            webappname: "admin-site"
            url: dev.github.com/admin
          - packagepath: "webapp"
            webappname: "super-admin-site"
            url: dev.github.com/super-admin


    with:
      ENVIRONMENT: "dev"
      ENVIRONMENT_URL: "${{ matrix.url }}"
      AZURE_WEBAPP_PACKAGE_PATH: "${{ matrix.packagepath }}"
      WEBAPP_NAME: ${{ matrix.webappname }}
      ARTIFACT_NAME: "webapp"
    secrets: inherit