name: Update Release Description

on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: write
  issues: read
  
  
jobs:
  update-release-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Release Description with Linked Issues
        uses: jcantosz/release-issues-action@main # Use the action defined in the repository
        with:
          github_token: ${{ secrets.PAT }}
          github_repository: ${{ github.repository }}
          github_release_tag: "v1.0.0"
