on:
  pull_request:

permissions:
  contents: write

jobs:
  write-to-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git checkout ${{ github.head_ref }}
          echo test >> test.yml
          git add .
          git commit -am "Update wiki"
          git push
